/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as NewRouteImport } from './routes/new'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesArticleIdRouteImport } from './routes/articles.$articleId'
import { Route as ArticlesNewRouteImport } from './routes/articles.new'
import { Route as DebateDebateIdRouteImport } from './routes/debate.$debateId'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as MessagesUsernameRouteImport } from './routes/messages.$username'
import { Route as UUsernameRouteImport } from './routes/u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleIdRoute = ArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesNewRoute = ArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DebateDebateIdRoute = DebateDebateIdRouteImport.update({
  id: '/debate/$debateId',
  path: '/debate/$debateId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesUsernameRoute = MessagesUsernameRouteImport.update({
  id: '/messages/$username',
  path: '/messages/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/leaderboard': typeof LeaderboardRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/debate/$debateId': typeof DebateDebateIdRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/u/$username': typeof UUsernameRoute
  '/articles/': typeof ArticlesIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/leaderboard': typeof LeaderboardRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/debate/$debateId': typeof DebateDebateIdRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/u/$username': typeof UUsernameRoute
  '/articles': typeof ArticlesIndexRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/leaderboard': typeof LeaderboardRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/debate/$debateId': typeof DebateDebateIdRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/u/$username': typeof UUsernameRoute
  '/articles/': typeof ArticlesIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/leaderboard'
    | '/new'
    | '/profile'
    | '/settings'
    | '/articles/$articleId'
    | '/articles/new'
    | '/debate/$debateId'
    | '/messages/$username'
    | '/u/$username'
    | '/articles/'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/leaderboard'
    | '/new'
    | '/profile'
    | '/settings'
    | '/articles/$articleId'
    | '/articles/new'
    | '/debate/$debateId'
    | '/messages/$username'
    | '/u/$username'
    | '/articles'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/leaderboard'
    | '/new'
    | '/profile'
    | '/settings'
    | '/articles/$articleId'
    | '/articles/new'
    | '/debate/$debateId'
    | '/messages/$username'
    | '/u/$username'
    | '/articles/'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  LeaderboardRoute: typeof LeaderboardRoute
  NewRoute: typeof NewRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  ArticlesArticleIdRoute: typeof ArticlesArticleIdRoute
  ArticlesNewRoute: typeof ArticlesNewRoute
  DebateDebateIdRoute: typeof DebateDebateIdRoute
  MessagesUsernameRoute: typeof MessagesUsernameRoute
  UUsernameRoute: typeof UUsernameRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleId': {
      id: '/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof ArticlesArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/new': {
      id: '/articles/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof ArticlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debate/$debateId': {
      id: '/debate/$debateId'
      path: '/debate/$debateId'
      fullPath: '/debate/$debateId'
      preLoaderRoute: typeof DebateDebateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$username': {
      id: '/messages/$username'
      path: '/messages/$username'
      fullPath: '/messages/$username'
      preLoaderRoute: typeof MessagesUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  LeaderboardRoute: LeaderboardRoute,
  NewRoute: NewRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  ArticlesArticleIdRoute: ArticlesArticleIdRoute,
  ArticlesNewRoute: ArticlesNewRoute,
  DebateDebateIdRoute: DebateDebateIdRoute,
  MessagesUsernameRoute: MessagesUsernameRoute,
  UUsernameRoute: UUsernameRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
